/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

/* Table schema:
CREATE TABLE kv_store_c9775fa5 (
  key TEXT NOT NULL PRIMARY KEY,
  value JSONB NOT NULL
);
*/
import { createClient } from "jsr:@supabase/supabase-js@2.49.8";
// View at https://supabase.com/dashboard/project/emxxkvjhmdimmpdzxyez/database/tables

const client = () => {
  console.log("URL EXISTS:", !!Deno.env.get("SUPABASE_URL"));
  console.log("SERVICE KEY EXISTS:", !!Deno.env.get("SUPABASE_SERVICE_ROLE_KEY"));

  return createClient(
    Deno.env.get("SUPABASE_URL")!,
    Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,
  );
};

export const get = async (key: string): Promise<any> => {
  const supabase = client();

  const { data, error } = await supabase
    .from("kv_store_c9775fa5")
    .select("value")
    .eq("key", key)
    .maybeSingle();

  if (error) {
    console.error("KV GET ERROR:");
    console.error(error);
    throw error;
  }

  return data?.value;
};

// Delete deletes a key-value pair from the database.
export const del = async (key: string): Promise<void> => {
  const supabase = client()
  const { error } = await supabase.from("kv_store_c9775fa5").delete().eq("key", key);
  if (error) {
    throw new Error(error.message);
  }
};

// Sets multiple key-value pairs in the database.
export const mset = async (keys: string[], values: any[]): Promise<void> => {
  const supabase = client()
  const { error } = await supabase.from("kv_store_c9775fa5").upsert(keys.map((k, i) => ({ key: k, value: values[i] })));
  if (error) {
    throw new Error(error.message);
  }
};

export const set = async (key: string, value: any): Promise<void> => {
  const supabase = client();

  const { error } = await supabase
    .from("kv_store_c9775fa5")
    .upsert({
      key,
      value,
    });

  if (error) {
    console.error("KV SET ERROR:");
    console.error(error);
    throw error;
  }
};

// Gets multiple key-value pairs from the database.
export const mget = async (keys: string[]): Promise<any[]> => {

  const supabase = client()
  const { data, error } = await supabase.from("kv_store_c9775fa5").select("value").in("key", keys);
  if (error) {
    throw new Error(error.message);
  }
  return data?.map((d) => d.value) ?? [];
};

// Deletes multiple key-value pairs from the database.
export const mdel = async (keys: string[]): Promise<void> => {
  const supabase = client()
  const { error } = await supabase.from("kv_store_c9775fa5").delete().in("key", keys);
  if (error) {
    throw new Error(error.message);
  }
};

// Search for key-value pairs by prefix.
export const getByPrefix = async (prefix: string): Promise<any[]> => {
  const supabase = client()
  const { data, error } = await supabase.from("kv_store_c9775fa5").select("key, value").like("key", prefix + "%");
  if (error) {
    throw new Error(error.message);
  }
  return data?.map((d) => d.value) ?? [];
};