import type { VotingCode } from '../types';
import * as XLSX from 'xlsx';
import jsPDF from 'jspdf';

function codesHeaders() {
  return ['CODE', 'CLASS', 'SECTION', 'ROLL NO', 'STATUS', 'USED AT', 'GENERATED AT', 'BATCH ID', 'GENERATED BY'];
}

function codeRow(c: VotingCode) {
  return [
    c.code,
    c.class,
    c.section,
    c.roll_number,
    c.status.toUpperCase(),
    c.used_at ? new Date(c.used_at).toLocaleString() : '',
    new Date(c.generated_at).toLocaleString(),
    c.batch_id,
    c.generated_by || '',
  ];
}

export function exportCSV(codes: VotingCode[], filename = 'voting-codes.csv'): void {
  const BOM = '﻿';
  const headers = codesHeaders().join(',');
  const rows = codes.map(c => codeRow(c).map(v => `"${v}"`).join(',')).join('\n');
  const content = BOM + headers + '\n' + rows;
  downloadBlob(new Blob([content], { type: 'text/csv;charset=utf-8;' }), filename);
}

export function exportTXT(codes: VotingCode[], filename = 'voting-codes.txt'): void {
  const separator = '─'.repeat(70);
  const lines = [
    'ST. MARTINS HIGH SCHOOL (SMHS)',
    'Pulse Voting System — Voting Code List',
    separator,
    `Generated: ${new Date().toLocaleString()}`,
    separator,
    '',
    ...codes.map(c =>
      `${c.code.padEnd(10)} | Class ${c.class}${c.section.padEnd(4)} | Roll ${String(c.roll_number).padEnd(5)} | ${c.status.toUpperCase().padEnd(8)} | ${c.used_at ? new Date(c.used_at).toLocaleString() : 'Not used'}`
    ),
    '',
    separator,
  ];
  downloadBlob(new Blob([lines.join('\n')], { type: 'text/plain;charset=utf-8;' }), filename);
}

export function exportXLSX(codes: VotingCode[], filename = 'voting-codes.xlsx'): void {
  const data = [codesHeaders(), ...codes.map(codeRow)];
  const ws = XLSX.utils.aoa_to_sheet(data);
  ws['!cols'] = codesHeaders().map(() => ({ wch: 20 }));
  const wb = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(wb, ws, 'Voting Codes');
  XLSX.writeFile(wb, filename);
}

export function exportPDF(codes: VotingCode[], electionName: string, electionYear: number): void {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const W = 210;
  const margin = 20;
  let y = margin;

  // Header
  doc.setFillColor(9, 9, 11);
  doc.rect(0, 0, W, 40, 'F');
  doc.setTextColor(124, 58, 237);
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text('ST. MARTINS HIGH SCHOOL (SMHS)', W / 2, y + 8, { align: 'center' });
  doc.setTextColor(168, 85, 247);
  doc.setFontSize(11);
  doc.text('Pulse Voting System — Official Code Report', W / 2, y + 16, { align: 'center' });
  doc.setTextColor(161, 161, 170);
  doc.setFontSize(9);
  doc.text(`${electionName} ${electionYear}`, W / 2, y + 22, { align: 'center' });

  y = 50;
  doc.setTextColor(161, 161, 170);
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.text(`Generated: ${new Date().toLocaleString()}    Total Codes: ${codes.length}`, margin, y);

  // Watermark
  doc.setTextColor(200, 200, 200);
  doc.setFontSize(50);
  doc.setFont('helvetica', 'bold');
  doc.text('OFFICIAL USE ONLY', W / 2, 150, { align: 'center', angle: -45 });
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(50, 50, 50);

  y += 8;
  // Table header
  doc.setFillColor(30, 30, 40);
  doc.rect(margin, y, W - margin * 2, 8, 'F');
  doc.setTextColor(250, 250, 250);
  doc.setFontSize(8);
  doc.setFont('helvetica', 'bold');
  const cols = [margin, 50, 65, 75, 90, 120, 155, 185];
  const headers = ['CODE', 'CLASS', 'SEC', 'ROLL', 'STATUS', 'USED AT', 'BATCH', 'BY'];
  headers.forEach((h, i) => doc.text(h, cols[i], y + 5.5));
  y += 10;

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(7.5);
  codes.forEach((c, i) => {
    if (y > 270) {
      doc.addPage();
      y = 20;
    }
    if (i % 2 === 0) {
      doc.setFillColor(245, 245, 250);
      doc.rect(margin, y - 1, W - margin * 2, 7, 'F');
    }
    doc.setTextColor(30, 30, 30);
    const row = [c.code, `Cls ${c.class}`, c.section, String(c.roll_number), c.status.toUpperCase(), c.used_at ? new Date(c.used_at).toLocaleTimeString() : '—', c.batch_id.substring(0, 10), c.generated_by?.substring(0, 8) || ''];
    row.forEach((v, j) => doc.text(String(v), cols[j], y + 4));
    y += 7;
  });

  // Signature block
  if (y > 240) { doc.addPage(); y = 20; }
  y += 10;
  doc.setDrawColor(150, 150, 150);
  doc.line(margin, y + 10, 90, y + 10);
  doc.setFontSize(8);
  doc.setTextColor(100, 100, 100);
  doc.text('Authorized Signature (Admin)', margin, y + 14);

  doc.save('SMHS-Voting-Codes-Report.pdf');
}

export function exportResultsPDF(results: import('../types').ElectionResults, electionName: string, electionYear: number): void {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const W = 210;
  const margin = 20;
  let y = margin;

  doc.setFillColor(9, 9, 11);
  doc.rect(0, 0, W, 40, 'F');
  doc.setTextColor(124, 58, 237);
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text('SMHS ELECTION RESULTS REPORT', W / 2, y + 10, { align: 'center' });
  doc.setTextColor(168, 85, 247);
  doc.setFontSize(11);
  doc.text(`${electionName} — ${electionYear}`, W / 2, y + 20, { align: 'center' });
  doc.setTextColor(161, 161, 170);
  doc.setFontSize(9);
  doc.text(`Generated: ${new Date().toLocaleString()}`, W / 2, y + 28, { align: 'center' });

  // Watermark
  doc.setTextColor(200, 200, 200);
  doc.setFontSize(50);
  doc.text('OFFICIAL RESULTS', W / 2, 150, { align: 'center', angle: -45 });

  y = 50;
  doc.setTextColor(50, 50, 50);
  doc.setFontSize(10);

  results.results.forEach(r => {
    if (y > 250) { doc.addPage(); y = 20; }
    doc.setFillColor(124, 58, 237);
    doc.rect(margin, y, W - margin * 2, 8, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(10);
    doc.text(`POSITION: ${r.role.toUpperCase()}`, margin + 3, y + 5.5);
    y += 12;

    doc.setTextColor(30, 30, 30);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11);
    doc.text(`Winner: ${r.winner?.name || 'TBD'} (${r.winner?.votes || 0} votes)`, margin, y);
    y += 8;

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    r.candidates.forEach(c => {
      doc.text(`  • ${c.name} — ${c.vote_count} votes`, margin + 5, y);
      y += 6;
    });
    y += 6;
  });

  y += 4;
  doc.setFillColor(230, 230, 240);
  doc.rect(margin, y, W - margin * 2, 0.5, 'F');
  y += 8;
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10);
  doc.text(`Total Votes Cast: ${results.total_votes}    Total Students: ${results.total_students}    Turnout: ${results.turnout_percent}%`, margin, y);

  y += 20;
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.text('Verified & Approved', margin, y);
  doc.setDrawColor(150);
  doc.line(margin, y + 10, 90, y + 10);
  doc.text('Signature (Principal / Election Committee)', margin, y + 14);

  doc.save('SMHS-Election-Results.pdf');
}

function downloadBlob(blob: Blob, filename: string): void {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

export function exportArchivePDF(archive: import('../types').ArchivedElection): void {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const W = 210;
  const margin = 20;
  let y = margin;

  doc.setFillColor(9, 9, 11);
  doc.rect(0, 0, W, 40, 'F');
  doc.setTextColor(124, 58, 237);
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text('SMHS ELECTION ARCHIVE REPORT', W / 2, y + 10, { align: 'center' });
  doc.setTextColor(168, 85, 247);
  doc.setFontSize(11);
  doc.text(`${archive.name} — ${archive.year}`, W / 2, y + 20, { align: 'center' });
  doc.setTextColor(161, 161, 170);
  doc.setFontSize(9);
  doc.text(`Archived: ${new Date(archive.archivedAt).toLocaleString()}`, W / 2, y + 28, { align: 'center' });

  y = 50;
  doc.setTextColor(50, 50, 50);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.text(`Total Votes: ${archive.totalVotes}    Total Students: ${archive.totalStudents}    Turnout: ${archive.turnoutPercent}%`, margin, y);
  y += 10;

  archive.results.forEach(r => {
    if (y > 250) { doc.addPage(); y = 20; }
    doc.setFillColor(124, 58, 237);
    doc.rect(margin, y, W - margin * 2, 8, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(10);
    doc.text(`POSITION: ${r.role.toUpperCase()}`, margin + 3, y + 5.5);
    y += 12;

    doc.setTextColor(30, 30, 30);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11);
    doc.text(`Winner: ${r.winner?.name || 'TBD'} (${r.winner?.votes || 0} votes)`, margin, y);
    y += 8;

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    r.candidates.forEach(c => {
      doc.text(`  • ${c.name} — ${c.vote_count} votes`, margin + 5, y);
      y += 6;
    });
    y += 6;
  });

  if (archive.houseResults && archive.houseResults.length > 0) {
    if (y > 240) { doc.addPage(); y = 20; }
    y += 8;
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11);
    doc.text('House Results:', margin, y);
    y += 8;
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    archive.houseResults.forEach(h => {
      doc.text(`  ${h.class}${h.section}: ${h.voted}/${h.total} (${h.percent}%)`, margin + 5, y);
      y += 6;
    });
  }

  y += 10;
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.text('Verified & Approved', margin, y);
  doc.setDrawColor(150);
  doc.line(margin, y + 10, 90, y + 10);
  doc.text('Signature (Principal / Election Committee)', margin, y + 14);

  doc.save(`SMHS-Archive-${archive.name.replace(/\s+/g, '-')}.pdf`);
}

export function exportArchiveXLSX(archive: import('../types').ArchivedElection): void {
  const data: (string | number)[][] = [
    ['Election Archive Report'],
    ['Election Name', archive.name],
    ['Year', archive.year],
    ['Election Date', new Date(archive.electionDate).toLocaleString()],
    ['Archived At', new Date(archive.archivedAt).toLocaleString()],
    ['Total Votes', archive.totalVotes],
    ['Total Students', archive.totalStudents],
    ['Turnout %', archive.turnoutPercent],
    [],
    ['Position', 'Candidate Name', 'Class', 'Section', 'Votes'],
  ];

  archive.results.forEach(r => {
    r.candidates.forEach((c, i) => {
      data.push([i === 0 ? r.role : '', c.name, c.class, c.section, c.vote_count]);
    });
  });

  if (archive.houseResults && archive.houseResults.length > 0) {
    data.push([]);
    data.push(['House Results']);
    data.push(['Class', 'Section', 'Voted', 'Total', 'Percent']);
    archive.houseResults.forEach(h => {
      data.push([h.class, h.section, h.voted, h.total, `${h.percent}%`]);
    });
  }

  const ws = XLSX.utils.aoa_to_sheet(data);
  ws['!cols'] = data[0].map(() => ({ wch: 20 }));
  const wb = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(wb, ws, 'Archive');
  XLSX.writeFile(wb, `SMHS-Archive-${archive.name.replace(/\s+/g, '-')}.xlsx`);
}

export function exportArchiveJSON(archive: import('../types').ArchivedElection): void {
  const blob = new Blob([JSON.stringify(archive, null, 2)], { type: 'application/json' });
  downloadBlob(blob, `SMHS-Archive-${archive.name.replace(/\s+/g, '-')}.json`);
}
